#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
BIN="$TMP_DIR/crys"
CRYS_HOME_DIR="$TMP_DIR/crys-home"
TEST_DIR="$TMP_DIR/work"

STDOUT_FILE="$TMP_DIR/stdout"
STDERR_FILE="$TMP_DIR/stderr"
STATUS=0

VERSION="$(cd "$ROOT_DIR" && shards version)"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

mkdir -p "$CRYS_HOME_DIR" "$TEST_DIR"

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  if [[ -f "$STDOUT_FILE" ]]; then
    printf -- '--- stdout ---\n' >&2
    cat "$STDOUT_FILE" >&2 || true
  fi
  if [[ -f "$STDERR_FILE" ]]; then
    printf -- '--- stderr ---\n' >&2
    cat "$STDERR_FILE" >&2 || true
  fi
  exit 1
}

run_cmd() {
  : >"$STDOUT_FILE"
  : >"$STDERR_FILE"
  set +e
  "$@" >"$STDOUT_FILE" 2>"$STDERR_FILE"
  STATUS=$?
  set -e
}

run_cmd_with_stdin() {
  local input_file="$TMP_DIR/input"
  printf '%b' "$1" >"$input_file"
  shift
  : >"$STDOUT_FILE"
  : >"$STDERR_FILE"
  set +e
  "$@" <"$input_file" >"$STDOUT_FILE" 2>"$STDERR_FILE"
  STATUS=$?
  set -e
}

assert_status() {
  local expected="$1"
  [[ "$STATUS" == "$expected" ]] || fail "expected status $expected, got $STATUS"
}

assert_stdout_eq() {
  local expected="$1"
  local actual
  actual="$(cat "$STDOUT_FILE")"
  [[ "$actual" == "$expected" ]] || fail "stdout mismatch"
}

assert_stderr_contains() {
  local expected="$1"
  grep -F -- "$expected" "$STDERR_FILE" >/dev/null || fail "stderr did not contain: $expected"
}

assert_stdout_contains() {
  local expected="$1"
  grep -F -- "$expected" "$STDOUT_FILE" >/dev/null || fail "stdout did not contain: $expected"
}

assert_file_eq() {
  local path="$1"
  local expected="$2"
  local actual
  actual="$(cat "$path")"
  [[ "$actual" == "$expected" ]] || fail "file content mismatch for $path"
}

printf 'Building crys for integration tests...\n'
crystal build "$ROOT_DIR/src/main.cr" -o "$BIN"

export CRYS_HOME="$CRYS_HOME_DIR"

printf 'Testing help output...\n'
run_cmd "$BIN" -h
assert_status 0
assert_stdout_contains 'Usage:'
run_cmd "$BIN" --help
assert_status 0
assert_stdout_contains 'Options:'
run_cmd "$BIN" --version
assert_status 0
assert_stdout_eq "crys ${VERSION}"
printf 'Testing line processing options...\n'
run_cmd_with_stdin 'alpha\nbeta\n' "$BIN" -n 'puts line.upcase'
assert_status 0
assert_stdout_eq $'ALPHA\nBETA'

run_cmd_with_stdin 'alpha\nbeta\n' "$BIN" -p 'line.upcase'
assert_status 0
assert_stdout_eq $'ALPHA\nBETA'

run_cmd_with_stdin 'a:b\nc:d\n' "$BIN" -a -F: 'puts f[1]'
assert_status 0
assert_stdout_eq $'b\nd'

run_cmd_with_stdin $'a\tb\n' "$BIN" -a -F $'\t' 'puts f[1]'
assert_status 0
assert_stdout_eq 'b'

printf 'Testing requires...\n'
run_cmd_with_stdin '{"a":1,"b":2}' "$BIN" -r json 'puts JSON.parse(ARGF)["b"].as_i'
assert_status 0
assert_stdout_eq '2'

printf 'Testing init/final and dump...\n'
run_cmd_with_stdin '1\n2\n3\n' "$BIN" --init 'sum = 0' -n 'sum += line.to_i' --final 'puts sum'
assert_status 0
assert_stdout_eq '6'

run_cmd "$BIN" --dump -p 'line.upcase'
assert_status 0
assert_stdout_contains '# generated by crys'
assert_stdout_contains 'line = begin'
assert_stdout_contains 'puts line'

count_cache_files() {
  if [[ -d "$CRYS_HOME_DIR/cache" ]]; then
    find "$CRYS_HOME_DIR/cache" -type f | wc -l | tr -d ' '
  else
    printf '0'
  fi
}

printf 'Testing build cache reuse...\n'
cache_before="$(count_cache_files)"
run_cmd_with_stdin 'cache\n' "$BIN" -n 'puts line.reverse.reverse'
assert_status 0
assert_stdout_eq 'cache'
run_cmd_with_stdin 'cache\n' "$BIN" -n 'puts line.reverse.reverse'
assert_status 0
assert_stdout_eq 'cache'
cache_after="$(count_cache_files)"
[[ $((cache_after - cache_before)) -eq 1 ]] || fail 'expected exactly one new cached binary for repeated identical code'

printf 'Testing Crystal flag pass-through...\n'
run_cmd_with_stdin 'ok\n' "$BIN" --release -n 'puts line'
assert_status 0
assert_stdout_eq 'ok'

run_cmd_with_stdin 'ok\n' "$BIN" --error-trace -n 'puts line'
assert_status 0
assert_stdout_eq 'ok'

run_cmd_with_stdin 'ok\n' "$BIN" -O2 -n 'puts line'
assert_status 0
assert_stdout_eq 'ok'

printf 'Testing file input concatenation...\n'
printf 'foo\n' >"$TEST_DIR/a.txt"
printf 'bar\n' >"$TEST_DIR/b.txt"
run_cmd "$BIN" -n 'puts line' "$TEST_DIR/a.txt" "$TEST_DIR/b.txt"
assert_status 0
assert_stdout_eq $'foo\nbar'

run_cmd "$BIN" -n 'puts "#{path}:#{line}"' "$TEST_DIR/a.txt" "$TEST_DIR/b.txt"
assert_status 0
printf -v expected_path_output '%s:foo\n%s:bar' "$TEST_DIR/a.txt" "$TEST_DIR/b.txt"
assert_stdout_eq "$expected_path_output"

printf 'Testing path variable for per-file runs...\n'
printf 'first\n' >"$TEST_DIR/path.txt"
run_cmd "$BIN" -i.bak -p '"#{path}:#{line}"' "$TEST_DIR/path.txt"
assert_status 0
assert_file_eq "$TEST_DIR/path.txt" "$TEST_DIR/path.txt:first"
assert_file_eq "$TEST_DIR/path.txt.bak" 'first'

printf 'Testing in-place edit without backup...\n'
printf 'foo\nbar\n' >"$TEST_DIR/inplace.txt"
run_cmd "$BIN" -i -p 'line.upcase' "$TEST_DIR/inplace.txt"
assert_status 0
assert_file_eq "$TEST_DIR/inplace.txt" $'FOO\nBAR'
[[ ! -e "$TEST_DIR/inplace.txt".bak ]] || fail 'unexpected backup file for -i without suffix'

printf 'Testing invalid combinations...\n'
run_cmd "$BIN" -i -p 'line.upcase'
assert_status 1
assert_stderr_contains '-i requires at least one file'

printf 'Testing fnr resets when same file appears twice in ARGV...\n'
printf 'x\ny\n' >"$TEST_DIR/fnr1.txt"
run_cmd "$BIN" -n 'puts fnr' "$TEST_DIR/fnr1.txt" "$TEST_DIR/fnr1.txt"
assert_status 0
assert_stdout_eq $'1\n2\n1\n2'

printf 'Testing fnr (per-file line number)...\n'
printf 'a\nb\n' >"$TEST_DIR/fnr2.txt"
run_cmd "$BIN" -n 'puts fnr' "$TEST_DIR/fnr1.txt" "$TEST_DIR/fnr2.txt"
assert_status 0
assert_stdout_eq $'1\n2\n1\n2'

printf 'Testing nr stays global across files...\n'
run_cmd "$BIN" -n 'puts nr' "$TEST_DIR/fnr1.txt" "$TEST_DIR/fnr2.txt"
assert_status 0
assert_stdout_eq $'1\n2\n3\n4'

printf 'Testing fnr with stdin equals nr...\n'
run_cmd_with_stdin 'p\nq\n' "$BIN" -n 'puts "#{nr}:#{fnr}"'
assert_status 0
assert_stdout_eq $'1:1\n2:2'

printf 'Testing nf with -a...\n'
run_cmd_with_stdin 'a:b:c\nx:y\n' "$BIN" -a -F: 'puts nf'
assert_status 0
assert_stdout_eq $'3\n2'

printf 'Testing regex separator -F/: +/...\n'
run_cmd_with_stdin $'a:  b\nc: d\n' "$BIN" -a '-F/: +/' 'puts f[1]'
assert_status 0
assert_stdout_eq $'b\nd'

printf 'Testing regex separator -F/[ \t]+/...\n'
run_cmd_with_stdin $'foo  bar\nbaz\tqux\n' "$BIN" -a '-F/[ \t]+/' 'puts f[1]'
assert_status 0
assert_stdout_eq $'bar\nqux'

printf 'Testing --select shortcut...\n'
run_cmd_with_stdin $'alpha\nerror\nbeta\n' "$BIN" --select 'line =~ /error/'
assert_status 0
assert_stdout_eq 'error'

printf 'Testing --map shortcut...\n'
run_cmd_with_stdin $'alpha\nbeta\n' "$BIN" --map 'line.upcase'
assert_status 0
assert_stdout_eq $'ALPHA\nBETA'

printf 'Testing --where prefilter...\n'
run_cmd_with_stdin $'ok\nerror\nwarning\n' "$BIN" -n --where 'line =~ /error|warn/' 'puts line'
assert_status 0
assert_stdout_eq $'error\nwarning'

printf 'Testing -N named fields...\n'
run_cmd_with_stdin $'alice:20\nbob:30\n' "$BIN" -a -F: -N 'name,age' 'puts "#{name}:#{age}"'
assert_status 0
assert_stdout_eq $'alice:20\nbob:30'

printf 'Testing --header row hash...\n'
run_cmd_with_stdin $'name,age\nalice,20\nbob,30\n' "$BIN" -a -F, --header --map 'row["name"]'
assert_status 0
assert_stdout_eq $'alice\nbob'

printf 'Testing --sum shortcut...\n'
run_cmd_with_stdin $'1\n2\n3\n' "$BIN" --sum 'line.to_i'
assert_status 0
assert_stdout_eq '6.0'

printf 'Testing --count shortcut...\n'
run_cmd_with_stdin $'x\ny\nz\n' "$BIN" --count
assert_status 0
assert_stdout_eq '3'

printf 'Testing --sum and --count with --where...\n'
run_cmd_with_stdin $'1\nfoo\n3\nbar\n' "$BIN" --where 'line =~ /^[0-9]+$/' --sum 'line.to_i' --count
assert_status 0
assert_stdout_eq $'4.0\n2'

printf 'Testing string separator backward compat with -F:...\n'
run_cmd_with_stdin $'a:b\nc:d\n' "$BIN" -a -F: 'puts f[1]'
assert_status 0
assert_stdout_eq $'b\nd'

printf 'All integration tests passed.\n'